export const programs = [
    "3D Animation",
    "911 & Emergency Services Communications",
    "Academic Upgrading",
    "Accounting",
    "Accounting & Finance",
    "Accounting & Payroll",
    "Acting for Camera & Voice",
    "Advanced Investigations & Enforcement",
    "Animation",
    "Art & Design Foundations",
    "Artificial Intelligence",
    "Arts and Science – University Transfer",
    "Asset Management",
    "Aviation Operations",
    "Aviation Safety",
    "Bachelor of Business Administration",
    "Bachelor of Computer Science",
    "Bachelor of Engineering (Software Engineering)",
    "Bachelor of Science – Cosmetic Science",
    "Behavioural Sciences",
    "Biotechnology – Advanced",
    "Brand Management",
    "Broadcasting – Radio",
    "Broadcasting – Television",
    "Building Systems Engineering Technician",
    "Business",
    "Business Administration – Financial Planning",
    "Business Administration – Human Resources",
    "Business Administration – International Business",
    "Business Administration – Management",
    "Business Administration – Marketing",
    "Business Administration – Purchasing & Supply Management",
    "Business Analytics",
    "Business Information Technology",
    "Business Management",
    "Business Management – Entrepreneurship & Innovation",
    "Business – Insurance",
    "Business – International Business",
    "Business – Marketing",
    "Business – Supply Chain & Operations",
    "Cannabis Regulation & Quality Assurance",
    "Chemical Engineering Technology",
    "Chemical Laboratory Technician",
    "Chemical Laboratory Technology – Pharmaceutical",
    "Child & Youth Care",
    "Child Development Practitioner",
    "Civil Engineering Technician",
    "Civil Engineering Technology",
    "Clinical Research",
    "Cloud Architecture & Administration",
    "Computer Engineering Technology",
    "Computer Programming",
    "Computer Programming & Analysis",
    "Computer Systems Technician",
    "Computer Systems Technology",
    "Cosmetic Science",
    "Cosmetic Techniques & Management",
    "Creative Advertising",
    "Cybersecurity & Threat Management",
    "Database Application Developer",
    "Digital & Social Media Marketing",
    "Documentary & Non-Fiction Media Production",
    "Documentary Filmmaking Institute",
    "Early Childhood Education",
    "Early Childhood Education (Accelerated)",
    "Electromechanical Engineering Technology – Automation",
    "Electronics Engineering Technician",
    "Electronics Engineering Technology",
    "Environmental Landscape Management",
    "Environmental Technician",
    "Environmental Technology",
    "Esports Marketing Management",
    "Esthetician",
    "Esthetics & Medical Spa Therapies",
    "Event & Media Production",
    "Event Management – Creative Design",
    "Fashion Arts",
    "Fashion Business",
    "Fashion Business Management",
    "Fashion Studies",
    "Financial Planning",
    "Financial Services Compliance Administration",
    "Financial Services – Client Services",
    "Financial Technology",
    "Fire Protection Engineering Technician",
    "Fire Protection Engineering Technology",
    "Firefighter, Pre-Service Education and Training",
    "Fitness & Health Promotion",
    "Flight Services",
    "Flight Services – Operations & Cabin Management",
    "Floral Design",
    "Fraud Examination & Forensic Accounting",
    "Game Art & Animation",
    "General Arts – English for Academic Purposes",
    "General Arts – One Year Certificate",
    "Global Business Management",
    "Global Hospitality Business Development",
    "Global Hospitality Operations Management",
    "Global Hospitality Sustainable Leadership",
    "Government Relations",
    "Graphic Design",
    "Honours Bachelor of Aviation Technology",
    "Honours Bachelor of Behavioural Psychology",
    "Honours Bachelor of Child Development",
    "Honours Bachelor of Commerce – Accounting & Finance",
    "Honours Bachelor of Commerce – Business Management",
    "Honours Bachelor of Commerce – Business Technology Management",
    "Honours Bachelor of Commerce – Financial Planning",
    "Honours Bachelor of Commerce – Human Resources Management",
    "Honours Bachelor of Commerce – International Business Management",
    "Honours Bachelor of Commerce – Marketing",
    "Honours Bachelor of Communications & Media",
    "Honours Bachelor of Crime & Intelligence Analysis",
    "Honours Bachelor of Data Science and Analytics",
    "Honours Bachelor of Design in Interactive Media",
    "Honours Bachelor of Health Administration",
    "Honours Bachelor of Information Technology Design and Management",
    "Honours Bachelor of Information Technology – Cybersecurity",
    "Honours Bachelor of Interdisciplinary Studies",
    "Honours Bachelor of Mental Health and Addiction",
    "Honours Bachelor of Science – Biotechnology",
    "Honours Bachelor of Science – Nursing",
    "Honours Bachelor of Science – Nursing (Bridge)",
    "Honours Bachelor of Science – Nursing (Fast track)",
    "Honours Bachelor of Technology – Software Development",
    "Honours Bachelor of Therapeutic Recreation",
    "Hospitality Foundations",
    "Hospitality – Hotel & Restaurant Services Management",
    "Human Resources Management",
    "Illustration",
    "Immigration Case Management",
    "Independent Music Production",
    "Independent Songwriting & Performance",
    "Infant & Early Child Mental Health",
    "Interactive Media Design",
    "International Business Management",
    "International Transportation & Customs",
    "Journalism",
    "Justice Administration Services",
    "Justice Administration Services (Articulated)",
    "Law Clerk",
    "Law Clerk (Accelerated)",
    "Liberal Arts University Transfer",
    "Library & Information Technician",
    "Library & Information Technician (Accelerated)",
    "Marketing & Communications Strategy",
    "Marketing Management",
    "Master of Artificial Intelligence Design & Development",
    "Mechanical Engineering Technician (Tool Design)",
    "Mechanical Engineering Technology – Building Sciences",
    "Mechanical Engineering Technology – Industrial Design",
    "Mechanical Technician – CNC Programming",
    "Medical Esthetics Nursing",
    "Mental Health Intervention",
    "Non-Profit & Social Sector Management",
    "Occupational Therapist Assistant and Physiotherapist Assistant",
    "Office Administration – Executive",
    "Office Administration – Health Services",
    "Office Administration – Legal",
    "Opticianry",
    "Paralegal",
    "Paralegal (Accelerated)",
    "Personal Support Worker",
    "Pharmaceutical Regulatory Affairs & Quality Operations",
    "Police Foundations",
    "Practical Nursing",
    "Pre-Business",
    "Pre-Health Sciences Pathway to Advanced Diplomas & Degrees",
    "Professional Accounting Practice",
    "Professional Selling",
    "Project Management – Environmental",
    "Project Management – Information Technology",
    "Public Administration",
    "Public Relations – Corporate Communications",
    "Real Property Administration (Assessment & Appraisal)",
    "Real Property Administration (Assessment & Appraisal) (Accelerated)",
    "Social Service Worker",
    "Social Service Worker (Accelerated)",
    "Social Service Worker – Gerontology",
    "Social Service Worker – Immigrants and Refugees",
    "Social Service Worker – Immigrants and Refugees (Accelerated)",
    "Sports, Entertainment & Event Marketing",
    "Supply Chain Management – Global Logistics",
    "Sustainable Business Management",
    "Sustainable Urban & Transportation Planning",
    "TESL 1",
    "TESL 2",
    "Technical Communication",
    "Tourism – Services Management – Global Tourism Business Specialization",
    "Tourism – Services Management – Travel Services Specialization",
    "Tourism – Travel Operations",
    "Veterinary Assistant",
    "Veterinary Technician",
    "Visual Content Creation",
    "Visual Effects for Film & Television",
    "Visual Merchandising Arts",
    "Workplace Safety & Prevention"
];